FregatMonitoring/FregatMonitoring/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('FregatMonitoringApp/', include('FregatMonitoringApp.urls')),
    path('admin/', admin.site.urls),
]

FregatMonitoring/FregatMonitoringApp/urls.py
from unicodedata import name
from django.urls import path

from . import views
from .views import MyLoginView
from django.contrib.auth.views import LogoutView

app_name = 'FregatMonitoringApp'
urlpatterns = [
    path('login/', MyLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='FregatMonitoringApp:login'), name='logout'),
    path('', views.index, name='index'),
    path('ErrorMessage/', views.error_message, name='error_message'),
    path('SorryPage/', views.sorry_page, name='sorry_page'),
    path('Furnace_1_info/', views.furnace_1_info, name='furnace_1_info'),
    path('Furnace_2_info/', views.furnace_2_info, name='furnace_2_info'),
    path('Furnace_info_r/<int:furnace_no>/', views.furnace_info_r, name='furnace_info_r'),
    path('FurnaceBaseTrends/<int:furnace_no>/', views.furnace_base_trends, name='furnace_base_trends'),
    path('FurnaceErrorsLog/<int:furnace_no>/', views.furnace_errors_log, name='furnace_errors_log'),
    path('FurnaceErrorsLogData/<int:furnace_no>/', views.furnace_errors_log_data, name='furnace_errors_log_data'),
    path('FurnaceBaseTrendsData/<int:furnace_no>/', views.furnace_base_trends_data, name='furnace_base_trends_data'),
    path('Automelts_info/<int:melt_id_1>/', views.auto_melts_types_info, name='auto_melts_types_info'),
    path('auto_melts_log/', views.auto_melts_log, name='auto_melts_log'),
    path('auto_melts_log_data/', views.auto_melts_log_data, name='auto_melts_log_data'),
    path('AutoMeltsSaveSettings/<int:melt_id_1>/<int:melt_id_2>/', views.auto_melts_save_settings, name='auto_melts_save_settings'),
    path('AutoMeltsSetPoints/', views.auto_melts_setpoints, name='auto_melts_setpoints'),
    path('AutoMeltsSetPoints/<int:furnace_num>/', views.auto_melts_save_setpoints, name='auto_melts_save_setpoints'),
    path('AutoMeltsAddSubstep/<str:melt_type>/<int:melt_step>/', views.auto_melts_add_substep, name='auto_melts_add_substep'),
    path('AutoMeltsDelSubstep/<str:melt_type>/<int:melt_step>/<int:melt_substep>/', views.auto_melts_del_substep, name='auto_melts_del_substep'),
    path('Furnace_info_s/<int:signal_index>/', views.furnace_info_s, name='furnace_info_s'),
    path('Furnace_info_a/<int:furnace_no>/', views.furnace_info_a, name='furnace_info_a'),
    path('ReportsPage/', views.reports_page, name='reports_page'),
    path('GasesUsage/<str:report_type>/', views.gases_usage_report, name='gases_usage_report'),
    path('getGasesUsageData_daily/', views.get_gases_usage_data_daily, name='get_gases_usage_data_daily'),
    path('getGasesUsageData_hourly/', views.get_gases_usage_data_hourly, name='get_gases_usage_data_hourly'),
    path('bottling_page/', views.bottling_page, name='bottling_page'),
    path('bottling_page_data/', views.bottling_page_data, name='bottling_page_data'),
    path('current_bottling_page/', views.current_bottling_page, name='current_bottling_page'),
    path('bottling_journal_data/', views.bottling_journal_data, name='bottling_journal_data'),
    path('shzm_page/', views.shzm_page, name='shzm_page'),
    path('shzm_journal_page/', views.shzm_journal_page, name='shzm_journal_page'),
    path('shzm_journal_page_data/', views.shzm_journal_page_data, name='shzm_journal_page_data'),
]   

FregatMonitoring/FregatMonitoringApp/views.py
from ast import Str
from calendar import month
from datetime import datetime, timedelta, date
import itertools
from multiprocessing import context
from os import curdir 

from django.db.models.query_utils import subclasses
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.views import LoginView
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect
from django.template import loader
from django.urls import reverse, reverse_lazy
from django.db.models import F
from django.shortcuts import get_object_or_404

from .models import Automelts, Avtoplavka_status, Avtoplavka_setpoints, Autoplavka_log, AutoMeltsInfo, Daily_gases_consumption 
from .models import Floattable, Gases_consumptions_per_day, Melttypes, Meltsteps, Substeps, Tagtable, Rarefaction_P2, Bottling
from .models import CurrentBottling, Furnace1_errors_log, Furnace2_errors_log, Melts
from .serializers import FloattableSerializer, AutomeltsSerializer, RarefactionP2Serializer

from . import furnace_errors
from .furnace_errors import furnace1_errors_list, furnace2_errors_list

class MyLoginView(LoginView):
    redirect_authenticated_user = True
    
    def get_success_url(self):
        return reverse_lazy('FregatMonitoringApp:index') 
    
    def form_invalid(self, form):
        messages.error(self.request,'Неправильное имя пользователя или пароль!')
        return self.render_to_response(self.get_context_data(form=form))

@login_required
def index(request):
    return furnace_1_info(request)

@login_required
def reports_page(request):
    template = loader.get_template('FregatMonitoringApp/reports_page.html')
    context = None

    return HttpResponse(template.render(context, request))

@login_required
def gases_usage_report(request, **kwards): #Загружает первоначальный шаблон отчёт с данными по умолчанию   
    template = loader.get_template('FregatMonitoringApp/gases_usage_report.html')
    
    if(kwards.get('report_type') == 'gases_usage_daily'): #Выбран посуточный отчёт
        start_period = (datetime.now()-timedelta(hours=30*24) ).strftime('%Y-%m-%dT%H:%M')#предыдущий месяц
        stop_period = datetime.now().strftime('%Y-%m-%dT%H:%M')#текущий момент
    elif(kwards.get('report_type') == 'gases_usage_per_day'): #Выбран почасовой отчёт
        start_period = (datetime.now()-timedelta(hours=24)).replace(hour=8,minute=0).strftime('%Y-%m-%dT%H:%M')#предыдущие сутки c 8.00
        stop_period = datetime.now().replace(hour=8,minute=0).strftime('%Y-%m-%dT%H:%M')#текущие сутки до 8.00
 
    context={
        'report_type': kwards.get('report_type'),
        'Start_time': start_period,
        'Stop_time': stop_period,
    }

    return HttpResponse(template.render(context, request))

@login_required
def get_gases_usage_data_hourly(request, **kwards):
    '''Выдаёт данные по запросу клиента за выбранный период по часам. 
       Считает почасовые расходы газов, на основе данных о мгновенных расходах, которые регистрируются в таблице БД FloatTable каждые 10 секунд'''
    
    if request.method == 'GET':
        start_period = datetime.strptime(request.GET['start'], '%Y-%m-%dT%H:%M').strftime('%Y-%m-%d %H:%M') 
        stop_period = datetime.strptime(request.GET['stop'], '%Y-%m-%dT%H:%M').strftime('%Y-%m-%d %H:%M') 
    
    def hourly_db_request(tag_name: Str, start_per, stop_per): #запрос к БД для подсчёта почасового расхода газа(или кислорода) за период
        tag_ind = Tagtable.objects.filter(tagname=tag_name)[0].tagindex #индекс интересующего сигнала
        response_1 = Gases_consumptions_per_day.objects.raw(
            ''' SELECT ROW_NUMBER() OVER(ORDER BY CONCAT(DATEFROMPARTS(DATEPART(year, CAST(DTm AS datetime)), DATEPART(month, CAST(DTm AS datetime)), 
					                                                   DATEPART(day, CAST(DTm AS datetime))
							                                          ), ' ', DATEPART(hour, CAST(DTm AS datetime)),':59')) AS id, 
                       CONCAT(DATEFROMPARTS(DATEPART(year, CAST(DTm AS datetime)), DATEPART(month, CAST(DTm AS datetime)), 
					                        DATEPART(day, CAST(DTm AS datetime))
							               ), ' ', DATEPART(hour, CAST(DTm AS datetime)),':59') AS data, 
                       SUM(TimeDiffVal) AS consumption,
                       (CASE TagName  
                          WHEN 'MEASURES\FL710_NG' THEN 'Gas_P1'
                          WHEN 'MEASURES\TI_810B' THEN 'Gas_P2'
                          WHEN 'MEASURES\O1Flow' THEN 'O2_P1'
                          WHEN 'MEASURES\O2Flow' THEN 'O2_P2'
                          WHEN 'MEASURES\OX_OX800' THEN 'O2_Furma'
                       END) AS GasName 

                FROM(
                     SELECT DATEADD(ms,Millitm,DateAndTime) AS DTm,
                            TagIndex, 
                            (CAST(Val as float)/3600)*DATEDIFF(MILLISECOND,
                                                               DateAdd(ms,Millitm,DateAndTime),
            	                                               DateAdd(ms,
                                                                       LAG(Millitm,1,NULL) OVER (PARTITION BY TagIndex ORDER BY DateAndTime DESC),
            			                                               LAG(DateAndTime,1,NULL) OVER (PARTITION BY TagIndex ORDER BY DateAndTime DESC)
            			                                               )
            	                                               )/1000 as TimeDiffVal
                     FROM [FRGV202X\Production].[FX_Hist].[db_owner].[FloatTable]
                     WHERE TagIndex=%s  AND DateAndTime > %s AND DateAndTime < %s
                     ) a            
                INNER JOIN [FRGV202X\Production].[FX_Hist].[db_owner].[TagTable] b ON a.TagIndex=b.TagIndex
                GROUP BY TagName, CONCAT(DATEFROMPARTS(DATEPART(year, CAST(DTm AS datetime)), DATEPART(month, CAST(DTm AS datetime)), 
					                     DATEPART(day, CAST(DTm AS datetime))
							            ), ' ', DATEPART(hour, CAST(DTm AS datetime)),':59')
                ORDER BY TagName, CAST(CONCAT(DATEFROMPARTS(DATEPART(year, CAST(DTm AS datetime)), DATEPART(month, CAST(DTm AS datetime)), 
					                    DATEPART(day, CAST(DTm AS datetime))
							            ), ' ', DATEPART(hour, CAST(DTm AS datetime)),':59') AS datetime);'''
        , [tag_ind, start_per, stop_per])

        return response_1


    gas_furnace_1_consumption = hourly_db_request('MEASURES\FL710_NG', start_period, stop_period)
    gas_furnace_2_consumption = hourly_db_request('MEASURES\TI_810B', start_period, stop_period)
    o2_furnace_1_consumption = hourly_db_request('MEASURES\O1Flow', start_period, stop_period)
    o2_furnace_2_consumption = hourly_db_request('MEASURES\O2Flow', start_period, stop_period)
    furma_consumption = hourly_db_request('MEASURES\OX_OX800', start_period, stop_period)

    consumptions = list()
    consumptions.append(("furnace_1_Gas", gas_furnace_1_consumption))
    consumptions.append(("furnace_1_O2", o2_furnace_1_consumption))
    consumptions.append(("furnace_2_Gas", gas_furnace_2_consumption))
    consumptions.append(("furnace_2_O2", o2_furnace_2_consumption))
    consumptions.append(("furma", furma_consumption ))

    series = list()
    for i in range(len(consumptions)):
        series.append([[consumptions[i][0]], []])
        for j in range(0, len(consumptions[i][1])):
            point={"date":str(consumptions[i][1][j].data), "value":round(consumptions[i][1][j].consumption, 2)}
            series[i][1].append(point)

    return JsonResponse(series, safe=False)
    
@login_required
def get_gases_usage_data_daily(request, **kwards):
    '''Выдаёт данные по запросу клиента за выбранный период по дням. Достаёт данные из заранее подготовленной таблицы в БД: DailyGasesConsumption.
       Таблица содержит суточные расходы газов, рассчитанные (на основе данных о мгновенных расходах) хранимой процедурой по заданию ежедневно в 23:59'''
      
    if request.method == 'GET':
        start_period = datetime.strptime(request.GET['start'], '%Y-%m-%dT%H:%M').strftime('%Y-%m-%d') 
        stop_period = datetime.strptime(request.GET['stop'], '%Y-%m-%dT%H:%M').strftime('%Y-%m-%d') 
    else:    
        start_period = (datetime.now()-timedelta(hours=30*24) ).strftime('%Y-%m-%d')#предыдущий месяц
        stop_period = datetime.now().strftime('%Y-%m-%d')#текущий момент
    
    gas_furnace_1_consumption = Daily_gases_consumption.objects.filter(gasname = 'Gas_P1').filter(data__range=(start_period,stop_period)).order_by('data')
    gas_furnace_2_consumption = Daily_gases_consumption.objects.filter(gasname = 'Gas_P2').filter(data__range=(start_period,stop_period)).order_by('data')
    o2_furnace_1_consumption = Daily_gases_consumption.objects.filter(gasname = 'O2_P1').filter(data__range=(start_period,stop_period)).order_by('data')
    o2_furnace_2_consumption = Daily_gases_consumption.objects.filter(gasname = 'O2_P2').filter(data__range=(start_period,stop_period)).order_by('data')
    furma_consumption = Daily_gases_consumption.objects.filter(gasname = 'O2_Furma').filter(data__range=(start_period,stop_period)).order_by('data')

    consumptions = list()
    consumptions.append(("furnace_1_Gas", gas_furnace_1_consumption))
    consumptions.append(("furnace_1_O2", o2_furnace_1_consumption))
    consumptions.append(("furnace_2_Gas", gas_furnace_2_consumption))
    consumptions.append(("furnace_2_O2", o2_furnace_2_consumption))
    consumptions.append(("furma", furma_consumption ))

    series = list()
    for i in range(len(consumptions)):
        series.append([[consumptions[i][0]], []])
        for j in range(0, len(consumptions[i][1])):
            ts = datetime.strptime(str(consumptions[i][1][j].data), "%Y-%m-%d")

FregatMonitoring/FregatMonitoringApp/templates/FregatMonitoringApp/SorryPage.html
{% extends "FregatMonitoringApp/base.html" %}

{% block error_message %}
<h1> Ой, этого пока нет! Но скоро обязательно будет! </h1>

{% endblock %}

FregatMonitoring/FregatMonitoringApp/templates/FregatMonitoringApp/auto_melts_info.html
{% extends "FregatMonitoringApp/base.html" %}

{% block auto_melts_log_scripts %}{% endblock %}

{% block left_side_bar%}
<div class="left-side-bar">
    <ul style="padding-left: 0px;">
      <li class="left-side-bar-list"><a href="{% url 'FregatMonitoringApp:auto_melts_types_info' 1 %}"> Режимы плавок </a></li>
      <li class="left-side-bar-list"><a href="{% url 'FregatMonitoringApp:auto_melts_log' %}"> Журнал плавок </a></li>      
      <li class="left-side-bar-list"><a href="{% url 'FregatMonitoringApp:auto_melts_setpoints' %}"> Уставки </a></li>
    </ul>
</div>
{% endblock%}   

{% block automelts_log %} {% endblock %}
{% block automelts_info %} {% endblock %}
{% block auto_melts_set_points%} {% endblock %}

FregatMonitoring/FregatMonitoringApp/templates/FregatMonitoringApp/base.html
{% load static %}

<html>
<head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
      <link rel="stylesheet" type="text/css" href="{% static 'FregatMonitoringApp/style.css' %}">
      {% block furnace_info_script %}{% endblock %}
      {% block furnace_trends_scripts %}{% endblock %}
      {% block auto_melts_log_scripts %}{% endblock %}
      {% block bottling_journal_scripts %}{% endblock %}
      {% block furnace_errors_log_scripts %}{% endblock %}
      {% block shzm_journal_scripts %}{% endblock %}
</head>
<body>

<div class="header-bgd"> <!-- Header-->
       <table width="100%">
       <tr style="height:20px">
          <td class="header-brand">ООО "Фрегат"</td>
          <td class="orange-text cursive">Cloud monitoring service</td>  
          <td class="white-text">Сервис дистанционного мониторинга и управления</td>
          <td><div>
            <table width="100%"> 
            <tr>
               <td><table>
                 <tr>
                   <td class="white-text" style="font-size: 14px"> Пользователь: </td>

                   <td class="white-text" style="font-size: 12px"> {{user}}     </td>
                 </tr>
                 <tr>
                   <td width=100рх> </td>
                   {% if user.is_authenticated %}
                   <td style="font-size: 12px"><a href="{% url 'FregatMonitoringApp:logout' %}" class="white-text"><i><u>Выйти</u></i></a></td>
                   {% else%}
                   <td style="font-size: 12px"><a href="{% url 'FregatMonitoringApp:login' %}" class="white-text"><i><u>Войти</u></i></a></td>
                   {% endif %}
                 </tr>
                    </table>
               </td>
            </tr>  
            <td>
               <td><table> 
                  <tr class="white-text">
                  </tr>    
                   </table> 
               </td>
            </tr>
            </table>
            </div>
          </td>
       </tr>
       </table>
</div>
<div class="main_container">  <!-- Содержимое полностью-->
  <div class="top_menu_bar">
    <a href="{% url 'FregatMonitoringApp:furnace_1_info' %}" class="top_menu_btn">Печь №1</a> 
    <a href="{% url 'FregatMonitoringApp:furnace_2_info' %}" class="top_menu_btn">Печь №2</a> 
    <a href="{% url 'FregatMonitoringApp:auto_melts_types_info' 1 %}" class="top_menu_btn">Автоплавка</a> 
    <a href="{% url 'FregatMonitoringApp:shzm_page' %}" class="top_menu_btn">ШЗМ</a> 
    <a href="{% url 'FregatMonitoringApp:bottling_page' %}" class="top_menu_btn">Розлив</a> 
    <a href="{% url 'FregatMonitoringApp:sorry_page' %}" class="top_menu_btn">Шнека</a> 
    <a href="{% url 'FregatMonitoringApp:reports_page' %}" class="top_menu_btn">Отчёты</a>    
  </div>
  {% block login %}{% endblock %}
  <div class="current_scr_container">
    <input id='curScr' type='hidden' value='monitor_scr'> 
    
    {% block left_side_bar %}{% endblock %}
    {% block error_message %}{% endblock %}
    {% block furnace_info %}{% endblock %}
    {% block furnace_base_trends%}{% endblock %}
    {% block furnace_errors_log%}{% endblock %}
    {% block reports%}{% endblock %}
    {% block automelts_log %}{% endblock %}
    {% block automelts_info %}{% endblock %}
    {% block melt_mod_card_info %}{% endblock %}
    {% block auto_melts_set_points %}{% endblock %}
    {% block bottling_journal %}{% endblock %}
    {% block current_bottling %}{% endblock %}
    {% block shzm_journal_page %}{% endblock %}
  </div>
</div>

</body>
</html>

FregatMonitoring/FregatMonitoringApp/templates/FregatMonitoringApp/bottling_page.html
{% extends "FregatMonitoringApp/base.html" %}

{% block bottling_journal_scripts %}{% endblock %}

{% block left_side_bar%}
<div class="left-side-bar">
    <ul style="padding-left: 0px;">
      <li class="left-side-bar-list"><a href="{% url 'FregatMonitoringApp:current_bottling_page' %}"> Текущий розлив </a></li>
      <li class="left-side-bar-list"><a href="{% url 'FregatMonitoringApp:bottling_page_data' %}"> Журнал розливов </a></li>      
      <li class="left-side-bar-list"><a href="{% url 'FregatMonitoringApp:auto_melts_setpoints' %}"> Назад </a></li>
    </ul>
</div>
{% endblock%}  

{% block bottling_journal %}{% endblock %}
  

FregatMonitoring/FregatMonitoringApp/templates/FregatMonitoringApp/detail.html
<form action="{% url 'FregatMonitoringApp:vote' question.id %}" method="post">
{% csrf_token %}
<fieldset>
    <legend><h1>{{ question.question_text }}</h1></legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
</fieldset>
<input type="submit" value="Vote">
</form>

FregatMonitoring/FregatMonitoringApp/templates/FregatMonitoringApp/error_message.html
{% extends "FregatMonitoringApp/base.html" %}

{% block error_message %}
<h1> Ой, что-то пошло не так! </h1>

{% endblock %}

FregatMonitoring/FregatMonitoringApp/templates/FregatMonitoringApp/furnace_errors_log_page.html
{% extends "FregatMonitoringApp/base.html" %}

{% block furnace_errors_log_scripts %}
<link href="https://unpkg.com/tabulator-tables/dist/css/tabulator.min.css" rel="stylesheet">
 <script type="text/javascript" src="https://unpkg.com/tabulator-tables/dist/js/tabulator.min.js"></script>
{% load static %}
{% endblock %}

{% block left_side_bar %}
<div class="left-side-bar">
    <ul style="padding-left: 0px;">
      {% if Furnace_No == 1 %}                                                                                            
          <li class="left-side-bar-list"><a href="{% url 'FregatMonitoringApp:furnace_base_trends' 1%}"> Тренды </a></li>
          <li class="left-side-bar-list"><a href="{% url 'FregatMonitoringApp:furnace_errors_log' 1%}"> Журнал ошибок </a></li>
      {% elif Furnace_No == 2%}
          <li class="left-side-bar-list"><a href="{% url 'FregatMonitoringApp:furnace_base_trends' 2%}"> Тренды </a></li>
          <li class="left-side-bar-list"><a href="{% url 'FregatMonitoringApp:furnace_errors_log' 2%}"> Журнал ошибок </a></li>
      {% endif %}
      <li class="left-side-bar-list"><a href="{% url 'FregatMonitoringApp:auto_melts_types_info' 1 %}"> Режимы плавок </a></li>
    </ul>
</div>
{% endblock%}  

{% block furnace_errors_log %}
<div class="content-box">
  <div id="FurErrlog" class="content-page-header">Журнал ошибок печи {{Furnace_No}}
    <div style="width: 20px;"></div>
    <div class="trend-period">Начальное время</div> 
    <input align="right" type="datetime-local"  id="start_time" name="start_time" value="{{ Start_time }}"/> 
    <div class="trend-period">Конечное время</div>
    <input align="right" type="datetime-local"  id="stop_time" name="stop_time" value="{{ Stop_time }}"/>
    <input class="btn" id="trend_update_btn" name="ChangeTrendPeriod_btn" value="загрузить" onclick=furnace_errors_log_update({{Furnace_No}})>
  </div>
  <div style="text-align: left"><span id="data-download-marker" hidden=true> Подождите. Идёт загрузка данных </span><span id="ddm1" hidden=true>.</span><span id="ddm2" hidden=true>.</span><span id="ddm3" hidden=true>.</span></div>
  <div id="furnace_errors_log_block" style="position: absolute;"> 
    <div id="furnace_errors_log_table" style="max-height: 700px;"></div>
  </div>    

  <script src="{% static 'FregatMonitoringApp/scripts/furnace_errors_log_update.js' %}"> </script>
</div>
{% endblock %}

FregatMonitoring/FregatMonitoringApp/templates/FregatMonitoringApp/gases_usage_report.html
{% extends "FregatMonitoringApp/reports_page.html" %}

{% block furnace_trends_scripts %}
    <script src="https://cdn.amcharts.com/lib/5/index.js"></script>
    <script src="https://cdn.amcharts.com/lib/5/percent.js"></script>
    <script src="https://cdn.amcharts.com/lib/5/xy.js"></script>
    <script src="https://cdn.amcharts.com/lib/5/themes/Animated.js"></script>
    <script src="https://cdn.amcharts.com/lib/5/themes/Kelly.js"></script>
    <script src="https://cdn.amcharts.com/lib/5/plugins/exporting.js"></script>
    
    <link href="https://unpkg.com/tabulator-tables@5.1.3/dist/css/tabulator.min.css" rel="stylesheet">
    <script type="text/javascript" src="https://unpkg.com/tabulator-tables@5.1.3/dist/js/tabulator.min.js"></script>
    <script type="text/javascript" src="https://oss.sheetjs.com/sheetjs/xlsx.full.min.js"></script>
    {% load static %}
    <!-- Скрипты обработки таблицы и графиков внизу шаблона -->     
{% endblock %}

{% block reports%}
<div class="content-box">
  <div id="Reports" class="content-page-header">Отчёты
    <div style="width: 200px;"></div>
    <div class="trend-period">Начальное время</div> 
    <input align="right" type="datetime-local"  id="start_time" name="start_time" value="{{ Start_time }}"/> 
    <div class="trend-period">Конечное время</div>
    <input align="right" type="datetime-local"  id="stop_time" name="stop_time" value="{{ Stop_time }}"/>
    <input class="btn" id="trend_update_btn" name="ChangeTrendPeriod_btn" value="обновить" onclick=GasesUsageDataUpdate()>
  </div>
  <span hidden id="report_type">{{ report_type }}</span>
  <div style="text-align: left"><span id="data-download-marker"> Подождите. Идёт загрузка данных </span><span id="ddm1">.</span><span id="ddm2">.</span><span id="ddm3">.</span></div>
  <div id="gases-usage-block"> 
    <div>  
      <button id="download-csv" >Download CSV</button>
      <button id="download-xlsx">Download XLSX</button>
    </div>
    <div id="gases-usage-table"></div>
  </div>    
  <div id="gases-usage-chartdiv"></div>
  <div id="gases-usage-summury">
    <div style="font-family: sans-serif;">Полный расход за весь период</div>
  </div>
  <div id="gases-usage-piechart-block">
    <div style="width: 50%;">
      <div style="font-family: sans-serif;"> <b>Природного газа:</b> <span id="PG_consumpt_sum"></span> м3</div>
      <div id="gas-usage-chartdiv"></div>
    </div>
    <div style="width: 50%;">
      <div style="font-family: sans-serif;"> <b>Кислорода:</b> <span id="O2_consumpt_sum"></span> м3</div>
      <div id="o2-usage-chartdiv"></div>
    </div>
    
    
  </div>
  <script src="{% static 'FregatMonitoringApp/scripts/GasesUsageCharts.js' %}"> </script>
  <script src="{% static 'FregatMonitoringApp/scripts/NaturalGasUsageCharts.js' %}"> </script>
  <script src="{% static 'FregatMonitoringApp/scripts/O2UsageCharts.js' %}"> </script>
  <script src="{% static 'FregatMonitoringApp/scripts/GasesUsageTable.js' %}"> </script>
</div>
{% endblock %}

FregatMonitoring/FregatMonitoringApp/templates/FregatMonitoringApp/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'FregatMonitoringApp:detail' question.id %}">Vote again?</a>

FregatMonitoring/FregatMonitoringApp/templates/FregatMonitoringApp/shzm_page.html
{% extends "FregatMonitoringApp/base.html" %}

{% block shzm_journal_scripts %}{% endblock %}

{% block left_side_bar%}
<div class="left-side-bar">
    <ul style="padding-left: 0px;">
      <li class="left-side-bar-list"><a href="{% url 'FregatMonitoringApp:shzm_journal_page' %}"> Журнал загрузок </a></li>      
      <li class="left-side-bar-list"><a href="{% url 'FregatMonitoringApp:shzm_page' %}"> Назад </a></li>
    </ul>
</div>
{% endblock%}  

{% block shzm_journal %}{% endblock %}