FregatMonitoring/FregatMonitoring/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('FregatMonitoringApp/', include('FregatMonitoringApp.urls')),
    path('admin/', admin.site.urls),
]

FregatMonitoring/FregatMonitoringApp/urls.py
from unicodedata import name
from django.urls import path

from . import views
from .views import MyLoginView
from django.contrib.auth.views import LogoutView

app_name = 'FregatMonitoringApp'
urlpatterns = [
    path('login/', MyLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='FregatMonitoringApp:login'), name='logout'),
    path('', views.index, name='index'),
    path('ErrorMessage/', views.error_message, name='error_message'),
    path('SorryPage/', views.sorry_page, name='sorry_page'),
    path('Furnace_1_info/', views.furnace_1_info, name='furnace_1_info'),
    path('Furnace_2_info/', views.furnace_2_info, name='furnace_2_info'),
    path('Furnace_info_r/<int:furnace_no>/', views.furnace_info_r, name='furnace_info_r'),
    path('FurnaceBaseTrends/<int:furnace_no>/', views.furnace_base_trends, name='furnace_base_trends'),
    path('FurnaceErrorsLog/<int:furnace_no>/', views.furnace_errors_log, name='furnace_errors_log'),
    path('FurnaceErrorsLogData/<int:furnace_no>/', views.furnace_errors_log_data, name='furnace_errors_log_data'),
    path('FurnaceBaseTrendsData/<int:furnace_no>/', views.furnace_base_trends_data, name='furnace_base_trends_data'),
    path('Automelts_info/<int:melt_id_1>/', views.auto_melts_types_info, name='auto_melts_types_info'),
    path('auto_melts_log/', views.auto_melts_log, name='auto_melts_log'),
    path('auto_melts_log_data/', views.auto_melts_log_data, name='auto_melts_log_data'),
    path('AutoMeltsSaveSettings/<int:melt_id_1>/<int:melt_id_2>/', views.auto_melts_save_settings, name='auto_melts_save_settings'),
    path('AutoMeltsSetPoints/', views.auto_melts_setpoints, name='auto_melts_setpoints'),
    path('AutoMeltsSetPoints/<int:furnace_num>/', views.auto_melts_save_setpoints, name='auto_melts_save_setpoints'),
    path('AutoMeltsAddSubstep/<str:melt_type>/<int:melt_step>/', views.auto_melts_add_substep, name='auto_melts_add_substep'),
    path('AutoMeltsDelSubstep/<str:melt_type>/<int:melt_step>/<int:melt_substep>/', views.auto_melts_del_substep, name='auto_melts_del_substep'),
    path('Furnace_info_s/<int:signal_index>/', views.furnace_info_s, name='furnace_info_s'),
    path('Furnace_info_a/<int:furnace_no>/', views.furnace_info_a, name='furnace_info_a'),
    path('ReportsPage/', views.reports_page, name='reports_page'),
    path('GasesUsage/<str:report_type>/', views.gases_usage_report, name='gases_usage_report'),
    path('getGasesUsageData_daily/', views.get_gases_usage_data_daily, name='get_gases_usage_data_daily'),
    path('getGasesUsageData_hourly/', views.get_gases_usage_data_hourly, name='get_gases_usage_data_hourly'),
    path('bottling_page/', views.bottling_page, name='bottling_page'),
    path('bottling_page_data/', views.bottling_page_data, name='bottling_page_data'),
    path('current_bottling_page/', views.current_bottling_page, name='current_bottling_page'),
    path('bottling_journal_data/', views.bottling_journal_data, name='bottling_journal_data'),
    path('shzm_page/', views.shzm_page, name='shzm_page'),
    path('shzm_journal_page/', views.shzm_journal_page, name='shzm_journal_page'),
    path('shzm_journal_page_data/', views.shzm_journal_page_data, name='shzm_journal_page_data'),
]   

FregatMonitoring/FregatMonitoringApp/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models

class Bottling(models.Model):
    id = models.BigAutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    proddate = models.DateTimeField(db_column='ProdDate', blank=True, null=True)
    grade = models.CharField(db_column='Grade', blank=True, null=True, max_length=50)
    weight = models.CharField(db_column='Weight', blank=True, null=True, max_length=50)
    lot = models.CharField(db_column='Lot', blank=True, null=True, max_length=50)
    bundle = models.CharField(db_column='Bundle', blank=True, null=True, max_length=50)

    class Meta:
        managed = False
        db_table = 'Zebra'

class CurrentBottling(models.Model):
    id = models.BigAutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    proddate = models.DateTimeField(db_column='ProdDate', blank=True, null=True)
    grade = models.CharField(db_column='Grade', blank=True, null=True, max_length=50)
    weight = models.CharField(db_column='Weight', blank=True, null=True, max_length=50)
    lot = models.CharField(db_column='Lot', blank=True, null=True, max_length=50)
    bundle = models.CharField(db_column='Bundle', blank=True, null=True, max_length=50)

    class Meta:
        managed = False
        db_table = 'CurrentBottlingTable'

class Daily_gases_consumption(models.Model):
    id = models.SmallIntegerField(db_column='Id', primary_key=True)
    data = models.DateField(db_column='Data', blank=False, null=False)
    daily_consumption = models.FloatField(db_column='Daily_consumption', blank=False, null=True)
    gasname = models.CharField(db_column='GasName', blank=False, null=False, max_length=20)

    class Meta:
        managed = False
        db_table = 'DailyGasesConsumption'

class Gases_consumptions_per_day(models.Model): #Модель для извлечения почасовых расходов газов за определённый период
    id = models.SmallIntegerField(primary_key=True)
    data = models.SmallIntegerField(blank=True, null=True)#номер часа, за который посчитан расход. Например, если расход вычислен за сутки, то в этом поле будут номера от 1 до 23
    consumption = models.FloatField(blank=True, null=True)
    gasname = models.CharField(blank=True, null=True, max_length=20)

    class Meta:
        managed = False
        db_table = 'GasesConsumptionsPerDay' #Такой таблицы в БД нет. Это нужно чтобы работал router на эту БД для этой модели

class Avtoplavka_status(models.Model):
    furnace_no = models.SmallIntegerField(db_column='furnace_no', primary_key=True)  # Field name made lowercase.
    auto_mode = models.BooleanField(db_column='auto_mode', blank=True, null=True)  # Field name made lowercase.
    melt_type = models.SmallIntegerField(db_column='melt_type', blank=True, null=True)  # Соответствует melt_num в Melttypes(вместе с furnace_no определяет плавку однозначно)
    current_step = models.SmallIntegerField(db_column='current_step', blank=True, null=True)  # соответствует step_num в Meltsteps
    current_substep = models.SmallIntegerField(db_column='current_substep', blank=True, null=True)  # соответствует sub_step_num в Substeps
    step_total_time = models.IntegerField(db_column='step_time_preset', blank=True, null=True)  # Field name made lowercase.
    step_time_remain = models.SmallIntegerField(db_column='current_step_time_remain', blank=True, null=True)  # Field name made lowercase.
    delta_t_curent = models.SmallIntegerField(db_column='delta_t_current', blank=True, null=True)  # Field name made lowercase.
    delta_t_stp = models.FloatField(db_column='delta_t_stp', blank=True, null=True)  # Field name made lowercase.
    hotflue_p_sp = models.FloatField(db_column='hotflue_p_sp', blank=True, null=True)  # Field name made lowercase.
    aspiration_p_sp = models.FloatField(db_column='aspiration_p_sp', blank=True, null=True)  # Field name made lowercase.
    melt_no = models.IntegerField(db_column='melt_no', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Avtoplavka_status'
       
class Avtoplavka_setpoints(models.Model):
    furnace_no = models.SmallIntegerField(db_column='furnace_no', primary_key=True)  #
    auto_mode = models.BooleanField(db_column='auto_mode', blank=True, null=True)  # 
    melt_type = models.SmallIntegerField(db_column='melt_type', blank=True, null=True)  # Соответствует melt_num в Melttypes(вместе с furnace_no определяет плавку однозначно)
    num_of_steps = models.SmallIntegerField(db_column='num_of_steps', blank=True, null=True) #
    num_of_substeps = models.SmallIntegerField(db_column='num_of_substeps', blank=True, null=True)  # 
    current_step_time = models.IntegerField(db_column='current_step_time', blank=True, null=True)  # 
    current_substep_time = models.SmallIntegerField(db_column='current_substep_time', blank=True, null=True)  # 
    delta_t_stp = models.SmallIntegerField(db_column='delta_t_stp', blank=True, null=True)  # 
    power_sp = models.SmallIntegerField(db_column='power_sp', blank=True, null=True)  # 
    rotation_sp = models.SmallIntegerField(db_column='rotation_sp', blank=True, null=True)  # 
    alpha_sp = models.SmallIntegerField(db_column='alpha_sp', blank=True, null=True)  # 

    class Meta:
        managed = False
        db_table = 'Avtoplavka_setpoints'

class Autoplavka_log(models.Model):
    log_id = models.IntegerField(db_column='log_id', primary_key=True)  # 
    furnace_no = models.SmallIntegerField(db_column='furnace_no')  #
    melt_number = models.SmallIntegerField(db_column='melt_number', blank=False, null=False) #Порядковый номер плавки по журналу Плавцеха
    melt_type = models.SmallIntegerField(db_column='melt_type', blank=True, null=True)  # Соответствует melt_num в Melttypes(вместе с furnace_no определяет плавку однозначно)
    current_step = models.SmallIntegerField(db_column='current_step', blank=True, null=True)  # соответствует step_num в Meltsteps
    current_substep = models.SmallIntegerField(db_column='current_substep', blank=True, null=True)  # соответствует sub_step_num в Substeps
    auto_mode = models.BooleanField(db_column='auto_mode', blank=True, null=True)  # 
    date_time = models.DateTimeField(db_column='date_time', blank=True, null=True)  # 

    class Meta:
        managed = False
        db_table = 'Autoplavka_log'

class Automelts(models.Model): #Пережиток прошлого в новых версиях не используется, начиная с перехода на версию _V4 в ПЛК автоплавки
    furnace_no = models.SmallIntegerField(db_column='Furnace_No', primary_key=True)  # Field name made lowercase.
    auto_mode = models.BooleanField(db_column='Auto_mode', blank=True, null=True)  # Field name made lowercase.
    melt_type = models.SmallIntegerField(db_column='Melt_type', blank=True, null=True)  # Соответствует melt_num в Melttypes(вместе с furnace_no определяет плавку однозначно)
    melt_step = models.SmallIntegerField(db_column='Melt_step', blank=True, null=True)  # соответствует step_num в Meltsteps
    step_total_time = models.IntegerField(db_column='Step_total_time', blank=True, null=True)  # Field name made lowercase.
    step_time_remain = models.SmallIntegerField(db_column='Step_time_remain', blank=True, null=True)  # Field name made lowercase.
    deltat = models.SmallIntegerField(db_column='DeltaT', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'AutoMelts'

class Melts(models.Model):
    id = models.BigAutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    meltno = models.IntegerField(db_column='MeltNo')  # Field name made lowercase.
    furnace = models.SmallIntegerField(db_column='Furnace')  # Field name made lowercase.
    total = models.FloatField(db_column='Total', blank=True, null=True)  # Field name made lowercase.
    pasta = models.FloatField(db_column='Pasta', blank=True, null=True)  # Field name made lowercase.
    coal = models.FloatField(db_column='Coal', blank=True, null=True)  # Field name made lowercase.
    soda = models.FloatField(db_column='Soda', blank=True, null=True)  # Field name made lowercase.
    iron = models.FloatField(db_column='Iron', blank=True, null=True)  # Field name made lowercase.
    dust = models.FloatField(db_column='Dust', blank=True, null=True)  # Field name made lowercase.
    oxides = models.FloatField(db_column='Oxides', blank=True, null=True)  # Field name made lowercase.
    slurry = models.FloatField(db_column='Slurry', blank=True, null=True)  # Field name made lowercase.
    fraction = models.FloatField(db_column='Fraction', blank=True, null=True)  # Field name made lowercase.
    pbmat = models.FloatField(db_column='PBMat', blank=True, null=True)  # Field name made lowercase.
    startmelt = models.DateTimeField(db_column='StartMelt', blank=True, null=True)  # Field name made lowercase.
    endmelt = models.DateTimeField(db_column='EndMelt', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Melts'

class Rarefaction(models.Model):
    id = models.BigAutoField(db_column='ID', primary_key=True)  # Field name made lowercase.
    rf_in_furnace = models.FloatField(db_column='Rf_in_furnace', blank=True, null=True)  # Field name made lowercase.
    rf_in_ciclone_2pech = models.FloatField(db_column='Rf_in_ciclone_2pech', blank=True, null=True)  # Field name made lowercase.
    timestamp = models.DateTimeField(db_column='TimeStamp')  # Field name made lowercase.

    class Meta:
        managed = False

FregatMonitoring/FregatMonitoringApp/templates/FregatMonitoringApp/include_templates/color_power_sp_if_reduce_template.html
<tr><td>Мощность</td>       <td>
                               <span id = {{ power_cur.1 }} class='UpdSign' style="color: {{power_color}};">{{power_cur.0|floatformat:0}}</span>
                               (<span id="power_sp_base" class='UpdSign_1' style="font-size: 11px"> {{ power_sp }} </span>) 
                            </td></tr>

FregatMonitoring/FregatMonitoringApp/templates/FregatMonitoringApp/include_templates/color_rarefaction_in_hotgate_template.html
<tr><td>Рязряжение</td>       <td>
                               {% if fur_no == 2 %}
                               <span id = {{ hotflue_p.1 }} class='UpdSign' style="color: {{p_cur_color}};">{{hotflue_p.0|floatformat:1}}</span>
                               {% else %}
                               <span id = "rf_fur2_point6" class='UpdSign_2' style="color: {{p_cur_color}};">{{hotflue_p|floatformat:1}}</span> <!--исправить id при переходе датчика в ШУ разряжений печи 1-->
                               {% endif %}
                               (<span id="hotflue_p_sp" class='UpdSign_1' style="font-size: 11px">{{ hotflue_p_sp|floatformat:1 }}</span>)<span> Па</span>
                            </td></tr>

FregatMonitoring/FregatMonitoringApp/templates/FregatMonitoringApp/include_templates/steps_templates.html
<table class="melt_step_container">
<tr>
<td id="stepid_{{step.step_id}}" class="area-name bottom-line" > {{ step.step_name }} </td>   
</tr>  
<tr><td> 
    <table> 
    {% if substeps|length > 0 %} 
    <tr><td width='70px'></td><td></td>
        <td></td>
        <td class="setpoints_text">Время</td>
        <td class="setpoints_text">Мощность</td>
        <td class="setpoints_text">Вращение</td>
        <td class="setpoints_text" >Обогащение</td>
        <td></td>
    </tr>
    {% else %}
    <tr><td width='70px'></td><td></td>
        <td></td>
        <td> Нет такой стадии в этой плавке</td>
        <td> </td>
        <td> </td>
        <td> </td>
        <td></td>
    </tr>
    {% endif %}
    {% for substep in substeps %}
        {% include "FregatMonitoringApp/include_templates/substeps_templates.html" %}
    {% endfor %} 
    <tr class="melt_step_add">
    <td> </td> <td>  </td><td>  </td><td>  </td><td>  </td><td>  </td> <td>  </td> 
    {% if user.is_authenticated and perms.FregatMonitoringApp.change_avtoplavka_setpoints %}
    <td><a href="{% url 'FregatMonitoringApp:auto_melts_add_substep' melt_name step.step_num %}" class="btn"> Добавить шаг</a></td>    
    {% endif %}  
    </tr>
    </table>
    </td>
</tr> 
</table>       
      

FregatMonitoring/FregatMonitoringApp/templates/FregatMonitoringApp/include_templates/substeps_templates.html
{% if substep.step == step %}
    <tr>  
    <td>  </td> <td>  </td>
    <td class="setpoints_text" width='70px'> Шаг {{read_only}} {{substep.sub_step_num}} </td> 
    {% if not user.is_authenticated or not perms.FregatMonitoringApp.change_avtoplavka_setpoints %}
       <td> <input readonly disabled name="Time_substepid_{{substep.substep_id}}" size="5" class="melt_setpoints" {% if substep.sub_step_time != 'null' %} value= {{substep.sub_step_time}}> {% else %} value="" {% endif %} </td> 
       <td> <input readonly disabled  name="Power_substepid_{{substep.substep_id}}" size="5" class="melt_setpoints" {% if substep.power_sp %} value= {{substep.power_sp}}> {% else %} value="" {% endif %} </td> 
       <td> <input readonly disabled  name="Rotation_substepid_{{substep.substep_id}}" size="5" class="melt_setpoints" {% if substep.rotation_sp %} value= {{substep.rotation_sp}}> {% else %} value="" {% endif %} </td> 
       <td> <input readonly disabled  name="Alpha_substepid_{{substep.substep_id}}" size="5" class="melt_setpoints" {% if substep.alpha_sp %} value= {{substep.alpha_sp}}> {% else %} value="" {% endif %} </td> 
    {% else %}
       <td> <input name="Time_substepid_{{substep.substep_id}}" size="5" class="melt_setpoints" {% if substep.sub_step_time != 'null' %} value= {{substep.sub_step_time}}> {% else %} value="" {% endif %} </td> 
       <td> <input name="Power_substepid_{{substep.substep_id}}" size="5" class="melt_setpoints" {% if substep.power_sp %} value= {{substep.power_sp}}> {% else %} value="" {% endif %} </td> 
       <td> <input name="Rotation_substepid_{{substep.substep_id}}" size="5" class="melt_setpoints" {% if substep.rotation_sp %} value= {{substep.rotation_sp}}> {% else %} value="" {% endif %} </td> 
       <td> <input name="Alpha_substepid_{{substep.substep_id}}" size="5" class="melt_setpoints" {% if substep.alpha_sp %} value= {{substep.alpha_sp}}> {% else %} value="" {% endif %} </td> 
    {% endif %}
    {% if substep.sub_step_num != 1 %}
      {% if user.is_authenticated and perms.FregatMonitoringApp.change_avtoplavka_setpoints %}
    <td> <a href="{% url 'FregatMonitoringApp:auto_melts_del_substep' melt_name step.step_num substep.sub_step_num %}" class="btn"> Удалить шаг </a></td>
      {% endif %}
    {% endif%}
    </tr>
{% endif %}  